import type { MinimapMessage } from "@/app/components/MinimapNavigator";
import type { Conversation } from "@/app/components/conversation/types";
import type { DataActions } from "./useConversationData";

export interface ConversationPageState extends DataActions {
  conversation: Conversation | null;
  setConversation: React.Dispatch<React.SetStateAction<Conversation | null>>;
  loading: boolean;
  setLoading: React.Dispatch<React.SetStateAction<boolean>>;
  input: string;
  setInput: React.Dispatch<React.SetStateAction<string>>;
  files: File[];
  setFiles: React.Dispatch<React.SetStateAction<File[]>>;
  scratchpadOpen: boolean;
  setScratchpadOpen: React.Dispatch<React.SetStateAction<boolean>>;
  goalPanelOpen: boolean;
  setGoalPanelOpen: React.Dispatch<React.SetStateAction<boolean>>;
  goalKickoff: { objective: string; nonce: number };
  setGoalKickoff: React.Dispatch<React.SetStateAction<{ objective: string; nonce: number }>>;
  todoPanelOpen: boolean;
  setTodoPanelOpen: React.Dispatch<React.SetStateAction<boolean>>;
  advancedOpen: boolean;
  setAdvancedOpen: React.Dispatch<React.SetStateAction<boolean>>;
  modelSettingsOpen: boolean;
  setModelSettingsOpen: React.Dispatch<React.SetStateAction<boolean>>;
  artifactPanelOpen: boolean;
  setArtifactPanelOpen: React.Dispatch<React.SetStateAction<boolean>>;
  selectedArtifactId: string | null;
  setSelectedArtifactId: React.Dispatch<React.SetStateAction<string | null>>;
  contextPanelOpen: boolean;
  setContextPanelOpen: React.Dispatch<React.SetStateAction<boolean>>;
  contextData: { usedTokens: number; maxContextTokens: number; contextPercent: number } | null;
  setContextData: React.Dispatch<React.SetStateAction<{ usedTokens: number; maxContextTokens: number; contextPercent: number } | null>>;
  toolErrorDialogOpen: boolean;
  setToolErrorDialogOpen: React.Dispatch<React.SetStateAction<boolean>>;
  keyboardShortcutsOpen: boolean;
  setKeyboardShortcutsOpen: React.Dispatch<React.SetStateAction<boolean>>;
  isCompressing: boolean;
  setIsCompressing: React.Dispatch<React.SetStateAction<boolean>>;
  searchProvider: "duckduckgo" | "tavily";
  toggleSearchProvider: () => void;
  enabledTools: string[];
  enabledSkills: string[];
  persistAdvanced: (next: { enabledTools: string[]; enabledSkills: string[] }) => void;
  selectedKbId: string;
  setSelectedKbId: React.Dispatch<React.SetStateAction<string>>;
  scrollRef: React.RefObject<HTMLDivElement | null>;
  toast: (msg: string, type: "success" | "error" | "info") => void;
  messages: any[];
  sendMessage: any;
  status: string;
  stop: () => void;
  regenerate: any;
  error: Error | undefined;
  setMessages: React.Dispatch<React.SetStateAction<any[]>>;
  addToolResult: any;
  isLoading: boolean;
  currentModelName: string;
  handleClarificationAnswer: (toolCallId: string, answer: string) => Promise<void>;
  handleEditMessage: (messageId: string, content: string) => Promise<void>;
  handleDeleteMessage: (messageId: string) => Promise<void>;
  handleCopyMessage: (content: string) => void;
  handleRegenerate: () => void;
  handleRegenerateMessage: (messageId: string) => void;
  handleRegenExecute: (mode: "retry" | "think" | "search", additionalInput: string) => Promise<void>;
  regenModal: {
    type: "retry" | "message";
    messageId?: string;
    userMessageText: string;
    userCreatedAt?: string;
    userMessageIdx?: number;
  } | null;
  setRegenModal: (v: any) => void;
  handleSubmit: (e: React.FormEvent<HTMLFormElement>) => Promise<void>;
  minimapMessages: MinimapMessage[];
  isDialogOpen: boolean;
  closeTopDialog: () => void;
}
